# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Drypatch
                                 A QGIS plugin
 This plugin detects dry patches from a satelite imagery layer 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-04
        copyright            : (C) 2024 by Tuhin Roychowdhury
        email                : rc.tuhin02@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Drypatch class from file Drypatch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dp_detector import Drypatch
    return Drypatch(iface)
